###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        container_name: geo-advert-board-mariadb
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - './:/application'
            - './storage/mysql-data:/var/lib/mysql/' #Save db-data to disc
        environment:
            - MYSQL_ROOT_PASSWORD=Aa123456789
            - MYSQL_DATABASE=geo-advert-board
            - MYSQL_USER=geo-advert-board
            - MYSQL_PASSWORD=Aa123456789
        ports:
            - '7511:3306'

    webserver:
        container_name: geo-advert-board-webserver
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '7512:80'
    
    meilisearch:
        container_name: geo-advert-board-meilisearch
        image: getmeili/meilisearch:v1.0.2
        environment:            
            - http_proxy
            - https_proxy
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
            - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
            - MEILI_ENV=${MEILI_ENV:-development}
            - MEILI_LOG_LEVEL
            - MEILI_DB_PATH=./storage/data.ms:/data.ms}
        ports:
            - 7513:7700
        volumes:
            - './:/application'
            - ./storage/data.ms:/data.ms        

    php-fpm:
        container_name: geo-advert-board-php-fpm
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
